sns_topic_arn: <%= ENV['SNS_TOPIC_ARN'] %>
aws_sns_access_key_id: <%= ENV['AWS_SNS_ACCESS_KEY_ID'] %>
aws_sns_secret_access_key: <%= ENV['AWS_SNS_SECRET_ACCESS_KEY'] %>
aws_sns_region: ap-northeast-1

